[package]
name = "passthrufs"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>", "François NT <francois@iobuffer.me>"]
edition = "2018"
workspace = ".."

[dependencies]
libc = "0.2"
log = "0.4"
fuser-ng = { path = ".." }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }

[features]
default = []
async = ["fuser-ng/async", "dep:tokio"]

[[bin]]
name = "async-passthrough"
path = "src/async_main.rs"
required-features = ["async"]
