name: Cargo Checks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Cargo checks (${{ matrix.rust_toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [stable, nightly]
        include:
          - rust_toolchain: stable
            deny_warnings: --deny warnings
          - rust_toolchain: nightly
            deny_warnings:
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Set up FUSE
        run: |
          sudo apt-get update
          sudo apt-get install --yes fuse libfuse-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust_toolchain}}
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- ${{matrix.deny_warnings}}

      - name: Run cargo test
        run: cargo test --workspace

      - name: Run doctests
        run: cargo test --doc
